_:
	cc -std=c11 noise.c -Wall -Werror -o noise -I /opt/homebrew/include -L /opt/homebrew/lib -llo
	c++ -std=c++11 terminal.cpp -Wall -Werror -o terminal -I /opt/homebrew/include -L /opt/homebrew/lib -llo -lncurses
