_:
	cc bubbles.c -Wall -Werror -o bubbles -I /opt/homebrew/include -L /opt/homebrew/lib -llo -lm
	cc stars.c -Wall -Werror -o stars -I /opt/homebrew/include -L /opt/homebrew/lib -llo -lm
	c++ -std=c++11 terminal.cpp -Wall -Werror -o terminal -I /opt/homebrew/include -L /opt/homebrew/lib -llo -lncurses
